### ISSUE TITLE
WBus to 3.3V

### ISSUE THREAD

**Issue by mihai-moldovan** [stuartpittaway/WebastoWBUSInterface#2]
Hi, 
this is not actually an issue, but I'm curious what would it take to modify you schematics to connect the WBus line to a 3.3V chip. My project architecture uses this board: https://www.nodemcu.com/index_en.html#fr_54747661d775ef1a3600009e to control the appliance. 
One way would be to add a 5v/3.3V TTL converter in front, but I presume there's a simpler way to modify the values of the components in your circuit.

Thanks.

**Comment by robertobuti** [comment]
It will work both with 5 or 3V3 power supply, uC side.
you don't need any traslator.
bye

**Comment by mihai-moldovan** [comment]
Awesome, thanks
