### ISSUE TITLE
commands examples

### ISSUE THREAD

**Issue by boelle** [stuartpittaway/WebastoWBUSInterface#3]
Hi

I plan to use this together with a raspberry pi as a pool heater (one of those intex frame pools), its the cheapest option compared to what the pool cost

Where can i look up the commands to send over serial and what i get back?

**Comment by boelle** [comment]
so far i found this: https://www.youtube.com/watch?v=6zZjSFef4yA

and an arduino sketch: https://pastebin.com/9jEW030e

out of luck in regards to a python script, so might be "forced" to have an arduino of sorts as the middle man

**Comment by stuartpittaway** [comment]
Hello, take a look at my VERY old code

https://github.com/stuartpittaway/WebastoHeaterWBusArduinoInterface

you have to send a start command and then send a "keep awake" command every few seconds afterwards.

**Comment by stuartpittaway** [comment]
Hello, take a look at my VERY old code

https://github.com/stuartpittaway/WebastoHeaterWBusArduinoInterface

you have to send a start command and then send a "keep awake" command every few seconds afterwards.

**Comment by boelle** [comment]
had a look at the code and i think i will manage

now looking at the kicad work you did, the jlc pcb part is most interesting, did you get boards made? and if so how did they turn out?

and if you have any left overs you know you will not use and want to get rid off i might be interested in

**Comment by stuartpittaway** [comment]
Yes the boards work, I also have some blank PCBs spare

**Comment by boelle** [comment]
how can i get in contact with you, i did try a google search for an email but no luck

**Comment by stuartpittaway** [comment]
Take a look at openenergyforum and drop me a note on therr

**Comment by boelle** [comment]
of course "facepalm"
